name: "Set Issue Label"
on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["/accept"]'
          labels: '["status/waiting-for-pr"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"